name: seckill_deal
description: A seckill deal flutter mobile project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.0.0
  dio: ^5.0.3
  retrofit: ^4.0.1
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  logger: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
