// ignore_for_file: file_names

import 'package:seckill_deal/res/strings.dart';

const Map<R, String> zhCN = {
  R.appName: '秒杀交易',
  R.loginTitle: '用户登录',
  R.registerTitle: '用户注册',
  R.login: '登录',
  R.register: '注册',
  R.loginHint: '登录手机号',
  R.registerHint: '注册手机号',
  R.passwordHint: '密码',
  R.needRegister: '没有账号，立即注册',
  R.loginEmptyError: '登录失败 : 手机号和密码不能为空!',
  R.registerEmptyError: '注册失败 : 手机号、密码和确定密码不能为空!',
  R.phoneFormatError: '登录失败 : 请输入正确的手机号!',
  R.registerFormatError: '注册失败 : 请输入正确的手机号和密码!',
  R.serverErrorMessage: '服务器异常',
  R.passwordConfirmHint: '确定密码',
  R.logout: '注销',
  R.inProgress: '已经开始',
  R.aboutToStart: '今日即将开始',
  R.distantFuture: '未来即将开始',
  R.hasEnded: '已结束',
  R.enterSeckillDetail: '进入秒杀详情',
  R.seckill: '立即秒杀',
  R.goodsDetail: '商品详情',
  R.orderPageTitle: '订单详情',
  R.updatePassword: '更改密码',
  R.oldPassword: '旧密码',
  R.newPassword: '新密码',
  R.confirmPassword: '确认新密码',
  R.cancel: '取消',
  R.summit: '发送',
  R.updateSuccess: '修改密码成功',
  R.updateError: '修改密码失败',
  R.networkError: '网络错误',
  R.unknownError: '未知错误',
};
